# Generated by Django 5.0.6 on 2024-06-03 15:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_remove_todoitem_created"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todoitem",
            name="completed",
        ),
        migrations.AddField(
            model_name="todoitem",
            name="content",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="todoitem",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
