# Generated by Django 5.1.3 on 2025-01-03 00:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_remove_todoitem_completed_todoitem_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="todoitem",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
