# Generated by Django 5.1.3 on 2025-01-03 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_category_alter_todoitem_options_todoitem_due_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AddField(
            model_name="category",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="todoitem",
            name="is_recurring",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="todoitem",
            name="last_recurring_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="todoitem",
            name="recurrence_interval",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Daily"),
                    (7, "Weekly"),
                    (14, "Bi-weekly"),
                    (30, "Monthly"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="todoitem",
            name="shared_with",
            field=models.ManyToManyField(
                blank=True, related_name="shared_todos", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="todoitem",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="todos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("name", "user")},
        ),
        migrations.CreateModel(
            name="TodoShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_shared", models.DateTimeField(auto_now_add=True)),
                ("can_edit", models.BooleanField(default=False)),
                (
                    "shared_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shared_with",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "todo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.todoitem"
                    ),
                ),
            ],
            options={
                "unique_together": {("todo", "shared_with")},
            },
        ),
    ]
