# Generated by Django 5.1.3 on 2025-01-03 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0007_todoitem_parent_todoitem_progress_todoattachment_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="todoitem",
            name="all_day",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="todoitem",
            name="color",
            field=models.CharField(default="primary", max_length=20),
        ),
        migrations.AddField(
            model_name="todoitem",
            name="last_notification_sent",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="todoitem",
            name="location",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name="NotificationSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_notifications", models.BooleanField(default=True)),
                (
                    "notification_time",
                    models.IntegerField(default=24, help_text="Hours before due date"),
                ),
                ("notify_on_assignment", models.BooleanField(default=True)),
                ("notify_on_completion", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("color", models.CharField(default="primary", max_length=20)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "user")},
            },
        ),
        migrations.AddField(
            model_name="todoitem",
            name="tags",
            field=models.ManyToManyField(blank=True, to="myapp.tag"),
        ),
    ]
