# Generated by Django 5.1.3 on 2025-01-03 01:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0008_todoitem_all_day_todoitem_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="todoitem",
            name="actual_hours",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="todoitem",
            name="blocked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="todoitem",
            name="blocked_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="todoitem",
            name="completion_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="todoitem",
            name="dependencies",
            field=models.ManyToManyField(
                blank=True, related_name="dependent_tasks", to="myapp.todoitem"
            ),
        ),
        migrations.AddField(
            model_name="todoitem",
            name="estimated_hours",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="todoitem",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="todoitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("backlog", "Backlog"),
                    ("todo", "To Do"),
                    ("in_progress", "In Progress"),
                    ("in_review", "In Review"),
                    ("done", "Done"),
                ],
                default="todo",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="todoitem",
            name="completed",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
